CREATE SCHEMA IF NOT EXISTS consumer_admin;
CREATE SCHEMA IF NOT EXISTS consumer;

CREATE TABLE IF NOT EXISTS consumer_admin.users(id BIGINT PRIMARY KEY, name varchar(20));

--DROP TABLE IF EXISTS consumer.address;

CREATE TABLE IF NOT EXISTS consumer.address(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  line1 varchar(64),
  line2 varchar(64),
  city varchar(64),
  state varchar(2),
  postal_code varchar(15));

--DROP TABLE IF EXISTS consumer.consumer;

CREATE TABLE IF NOT EXISTS consumer.consumer(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(30),
    last_name varchar(30),
    ssn_hash varchar(128),
    dob DATE,
    email varchar(64),
    address_id BIGINT,
    FOREIGN KEY (address_id) REFERENCES address(id));

