CREATE SCHEMA IF NOT EXISTS consumer_admin;
CREATE SCHEMA IF NOT EXISTS consumer;

CREATE TABLE IF NOT EXISTS consumer_admin.users(id BIGINT PRIMARY KEY, name varchar(20));

--DROP TABLE IF EXISTS consumer.consumer;

CREATE TABLE IF NOT EXISTS consumer.consumer(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(30),
    last_name varchar(30),
    ssn_hash varchar(128),
    dob DATE,
    email varchar(64)
);

ALTER TABLE consumer.consumer add CONSTRAINT IF NOT EXISTS "CONSUMER_SSN" unique (ssn_hash);

-- DROP TABLE IF EXISTS consumer.address;

CREATE TABLE IF NOT EXISTS consumer.address(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  consumer_id BIGINT,
  line1 varchar(64),
  line2 varchar(64),
  city varchar(64),
  state varchar(2),
  postal_code varchar(15),
  FOREIGN KEY (consumer_id) REFERENCES consumer(id)
  );
